apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: 02-traffic-routing
  labels:
    app: ratings
    scenario: 02-traffic-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      scenario: 02-traffic-routing
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        scenario: 02-traffic-routing
        version: v1
    spec:
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.3
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: 02-traffic-routing
  labels:
    app: ratings
    scenario: 02-traffic-routing
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
    scenario: 02-traffic-routing
