apiversion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels: 
    app: productpage
    scenario: "01-base-bookinfo"
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: productpage
      scenario: "01-base-bookinfo" 
      version: v1
  template:
    metadata: 
      labels: 
        app: productpage
        scenario: "01-base-bookinfo"
        version: v1 
    spec: 
      containers: 
      - name: productpage
        image:  docker.io/istio/examples-bookinfo-productpage-v1:1.20.3
        ports: 
        - containers: 9080

---          
apiVersion: v1 
kind: Service
metadata:
  name: productpage
  namespace: bookinfo-base
  labels: 
    app: productpage
    scenario: "01-base-bookinfo"
spec: 
  ports: 
  - port: 9080
    name: http
  selector: 
    app: productpage 
    scenario: "01-base-bookinfo" 