apiVersion: apps/v1
kind: Deployment
metadata: 
  name: reviews-v1
  namespace: bookinfo-base
  labels: 
    app: reviews
    scenario: "01-base-bookinfo"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: reviews 
      scenario: "01-base-bookinfo"
      version: v1 
  template:
    metadata:
      labels: 
        app: reviews
        scenario: "01-base-bookinfo"
        version: v1 
    spec: 
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.20.3
        ports: 
        - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: bookinfo-base
  labels:
    app: reviews
    scenario: "01-base-bookinfo"
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
    scenario: "01-base-bookinfo"                   