apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: 03-canary-deployment
  labels:
    app: reviews
    version: v2
    scenario: 03-canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
      scenario: 03-canary-deployment
  template:
    metadata:
      labels:
        app: reviews
        version: v2
        scenario: 03-canary-deployment
    spec:
      containers:
        - name: reviews
          image: docker.io/istio/examples-bookinfo-reviews-v2:1.20.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
